version: '4'

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_LISTENERS: INTERNAL://kafka:9092, CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_NODE_ID: 1
      CLUSTER_ID: ${KAFKA_CLUSTER_ID:-MKU30EVBNTcwNTJENDM2Qk}
      KAFKA_KRAFT_MODE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
    ports:
      - "9092:9092"
    restart: always

  kafka-ui:
      image: provectuslabs/kafka-ui:latest
      container_name: kafka-ui
      ports:
        - "8081:8080"
      environment:
        KAFKA_CLUSTERS_0_NAME: "test-single-kraft"
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
        KAFKA_UI_AUTH_ENABLED: "false"
      depends_on:
      - kafka